package main;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author NickZa555
 */

class GadientPanel extends javax.swing.JPanel {
    protected void paintComponent(Graphics g){
        Graphics2D g2d = (Graphics2D) g;
        int width = getWidth();
        int height = getHeight();
        
        Color color1 = new Color(25,0,51);
        Color color2 = new Color(75,0,153);
        GradientPaint gp = new GradientPaint(0,0,color1,180,height,color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, width, height);
    }
    
}




public class SettingPanel extends GadientPanel {
	
	public static boolean OctalIsSelect = true;
	public static boolean DeciIsSelect = true;
	public static boolean HexIsSelect = true;

	private Game frame;
    /**
     * Creates new form SettingPanel
     */
    public SettingPanel(Game frame) {
    	this.frame = frame;
        initComponents();
        set();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        SettingLabel = new javax.swing.JLabel();
        SpeedLabel1 = new javax.swing.JLabel();
        SpeedSlider = new javax.swing.JSlider(1,6,2);
        EnemyTypeLabel = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        VolumeLabel = new javax.swing.JLabel();
        SoundEffectLabel = new javax.swing.JLabel();
        soundSlider = new javax.swing.JSlider(0,100,30);
        BGmusicLabel = new javax.swing.JLabel();
        musicSlider = new javax.swing.JSlider(0,100,5);
        ApplyLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(25, 0, 51));
        setPreferredSize(new java.awt.Dimension(1600, 900));

        SettingLabel.setFont(new java.awt.Font("MV Boli", 1, 100)); // NOI18N
        SettingLabel.setForeground(new java.awt.Color(255, 204, 0));
        SettingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SettingLabel.setText("Settings");
        SettingLabel.setPreferredSize(new java.awt.Dimension(420, 80));

        SpeedLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        SpeedLabel1.setForeground(new java.awt.Color(255, 204, 0));
        SpeedLabel1.setText("Speed");
        SpeedLabel1.setPreferredSize(new java.awt.Dimension(420, 80));

        SpeedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpeedSliderStateChanged(evt);
            }
        });

        EnemyTypeLabel.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        EnemyTypeLabel.setForeground(new java.awt.Color(255, 204, 0));
        EnemyTypeLabel.setText("Enemy Type");
        EnemyTypeLabel.setPreferredSize(new java.awt.Dimension(420, 80));

        jCheckBox1.setFont(new java.awt.Font("MV Boli", 2, 24)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Octal (0o)");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("MV Boli", 2, 24)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Decimal (0d)");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setFont(new java.awt.Font("MV Boli", 2, 24)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 204, 0));
        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Hexadecimal (0x)");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        VolumeLabel.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        VolumeLabel.setForeground(new java.awt.Color(255, 204, 0));
        VolumeLabel.setText("Volume");
        VolumeLabel.setPreferredSize(new java.awt.Dimension(420, 80));

        SoundEffectLabel.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        SoundEffectLabel.setForeground(new java.awt.Color(255, 204, 0));
        SoundEffectLabel.setText("Sound Effect");
        SoundEffectLabel.setPreferredSize(new java.awt.Dimension(420, 80));

        soundSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                soundSliderStateChanged(evt);
            }
        });

        BGmusicLabel.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        BGmusicLabel.setForeground(new java.awt.Color(255, 204, 0));
        BGmusicLabel.setText("Background Music");
        BGmusicLabel.setPreferredSize(new java.awt.Dimension(420, 80));

        musicSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                musicSliderStateChanged(evt);
            }
        });

        ApplyLabel.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        ApplyLabel.setForeground(new java.awt.Color(255, 204, 0));
        ApplyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ApplyLabel.setText("Apply");
        ApplyLabel.setPreferredSize(new java.awt.Dimension(420, 80));
        ApplyLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ApplyLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ApplyLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ApplyLabelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SpeedLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnemyTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(VolumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(146, 146, 146))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BGmusicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SoundEffectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(118, 118, 118))
                            .addComponent(musicSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soundSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(502, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SettingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ApplyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216)))
                .addGap(502, 502, 502))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(SettingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(VolumeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SoundEffectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(soundSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BGmusicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(musicSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(SpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SpeedLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addComponent(EnemyTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(ApplyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
                
    }// </editor-fold>                        

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	OctalIsSelect = jCheckBox1.isSelected();
    }                                          

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	DeciIsSelect = jCheckBox2.isSelected();
    }                                          

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	HexIsSelect = jCheckBox3.isSelected();
    }                                          

    private void ApplyLabelMousePressed(java.awt.event.MouseEvent evt) {                                        
       frame.switchToMenu();
    }                                       

    private void SpeedSliderStateChanged(javax.swing.event.ChangeEvent evt) {                                         
    	frame.gameLogic.speedMultiplier = (float) SpeedSlider.getValue()/2;
    }                                        

    private void soundSliderStateChanged(javax.swing.event.ChangeEvent evt) {                                         
    	if (frame.sm.sound != null && frame.sm.soundVolumeControl != null) {
            frame.sm.setSoundVolume(soundSlider.getValue());
        }
    }                                        

    private void musicSliderStateChanged(javax.swing.event.ChangeEvent evt) {                                         
    	if (frame.sm.music != null && frame.sm.musicVolumeControl != null) {
            frame.sm.setMusicVolume(musicSlider.getValue());
        }
    }                                        

    private void ApplyLabelMouseEntered(java.awt.event.MouseEvent evt) {                                        
        ApplyLabel.setForeground(ApplyLabel.getForeground().brighter().brighter());
    }                                       

    private void ApplyLabelMouseExited(java.awt.event.MouseEvent evt) {                                       
        ApplyLabel.setForeground(ApplyLabel.getForeground().darker().darker());
    }                                        


    private void set() {
    	setTransparent();
    	SpeedSlider.setMajorTickSpacing(1);
    }
    
    private void setTransparent() {
    	SpeedSlider.setOpaque(false);
        jCheckBox1.setOpaque(false);
        jCheckBox2.setOpaque(false);
        jCheckBox3.setOpaque(false);
        soundSlider.setOpaque(false);
        musicSlider.setOpaque(false);

	}
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel ApplyLabel;
    private javax.swing.JLabel BGmusicLabel;
    private javax.swing.JLabel EnemyTypeLabel;
    public javax.swing.JSlider musicSlider;
    private javax.swing.JLabel SettingLabel;
    private javax.swing.JLabel SoundEffectLabel;
    public javax.swing.JSlider soundSlider;
    private javax.swing.JLabel SpeedLabel1;
    private javax.swing.JSlider SpeedSlider;
    private javax.swing.JLabel VolumeLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    // End of variables declaration                   
}
